### ISSUE TITLE
client.CallOverHTTP() error

### ISSUE THREAD

**Issue by zhcong** [yeqown/rpc#2]
when try to decode into jsonResponseArray, it say "base64.StdEncoding.Decode(base64Dst, data) got err: illegal base64 data at input byte 6".
It received the "Method Not Allowed".

**Comment by yeqown** [comment]
@zhcong  could you provide an example for me to debug?

**Comment by zhcong** [comment]
Sorry, I do my work by POST request now. I build rpc server with `jayson` in nodejs before, and rpc libary received `Method Not Allowed`, I think that's the key.

**Comment by yeqown** [comment]
oh~, currently this repo does not support the case:
> using a different server or client in another language
that means you have to use this repo's `client` and `server` at the same time.

because `codec` encode and decode method includes base64 encode ~, tha't my fault
```go
func (j *jsonCodec) Encode(argv interface{}) ([]byte, error) {
	// byts, err := json.Marshal(argv)
	j.encBuf.Reset()
	err := j.enc.Encode(argv)
	if err != nil {
		return nil, fmt.Errorf("json.Marshal(argv) got err: %v", err)
	}
	byts := j.encBuf.Bytes()
	base64Dst := make([]byte, base64.StdEncoding.EncodedLen(len(byts)))
	base64.StdEncoding.Encode(base64Dst, byts)
	// println(string(byts), len(byts), string(base64Dst), len(base64Dst))

	return base64Dst, nil
}
```
so you'd better change another repo(https://www.gorillatoolkit.org/pkg/rpc) for `jsonrpc`. 
if you want to provide some `PR`, I would be happy to receive the request ~

**Comment by zhcong** [comment]
Thanks for reply.
